laravel/envoy

src/Console/SshCommand.php
the precedence concatenation operator (`.`) is higher than the ternary operator (`?:`), so the ssh command concat expresion has a fault.
an example:
```php
php > $host = 'foo';
php > $cmd = 'ssh ' . $host ?: 'bar';
php > echo $cmd, PHP_EOL;
ssh foo
php > $host = '';
php > $cmd = 'ssh ' . $host ?: 'bar';
php > echo $cmd, PHP_EOL;
ssh
php >
```
=> Fix ssh command concat error

readme.md, src/Slack.php
The Slack WebHook has changed since the newest Envoy was released. It now takes the format of like this:
- `https://hooks.slack.com/services/ZZZZZZZZZ/YYYYYYYYY/XXXXXXXXXXXXXXX`
However the payload is the same. I simply removed the now defunct `team` argument and added the `hook` instead. `Hook` implies the entire url, I did it this way because that's how Slack presents it to you in the integrations page.
Also I updated the relevant documentation.
=> Updated the Slack command fit the new Slack WebHook Integration

src/Hipchat.php
If the message contains HTML tags, set the message format accordingly. This allows us to use HTML tags which are allowed by the API: https://www.hipchat.com/docs/api/method/rooms/message
=> Allow HTML message for Hipchat

src/RemoteProcessor.php
@taylorotwell This is a first pass at getting this working. I'm sure you could come up with a more elegant way of doing it. The main idea is that I'd like to use Envoy to handle a deploy process and the first step is to run some commands locally before running the deploy commands remotely. We don't want to have Node dependencies or the build process on remote servers so we need to run all those processes on the local machine prior to deploy (which is essentially an rsync operation). This patch just bypasses the SSH process when the `$target` is a localhost hostname.
Below is an example `Envoy.blade.php` that will run tasks and macros using this patch. An example run would be something like `envoy run installer`.
```php
@servers([ 'vagrant' => '127.0.0.1' ])
@task('init')
git commit -am …
```
=> Added ability to run scripts locally without SSH.

src/TaskContainer.php
Currently, when attempting to run a task or use a server that is not defined, envoy just fails with a PHP notice :
```
thibaud@thibaud-zbox [ ~/wks/project ] $ envoy run deploy
PHP Notice:  Undefined index: on in /home/thibaud/.composer/vendor/laravel/envoy/src/TaskContainer.php on line 225
PHP Stack trace:
PHP   1. {main}() /home/thibaud/.composer/vendor/laravel/envoy/envoy:0
PHP   2. Symfony\Component\Console\Application->run() /home/thibaud/.composer/vendor/laravel/envoy/envoy:11
PHP   3. Symfony\Component\Console\Application->doRun() /home/thibaud/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /home/thibaud/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP …
```
=> Add meaningful error messages for undefined tasks/servers/macros

src/TaskContainer.php
This prevents envoy from throwing exception if no macro exists for a given task name, which blocks envoy from checking if a task actually exists.
=> Remove exception if there's no macro

Envoy.blade.php, src/Console/Command.php, src/Console/RunCommand.php, src/Task.php, src/TaskContainer.php
Added functionality to set a confirmation message in a task.
I find this pretty useful if you're running a destructive task (overwriting db, deploying to production etc).
Uses the symfony askConfirmation function from the dialog helper.
=> Allow optional confirm message before running a task.

src/RemoteProcessor.php
I had a problem with running the command below with Envoy:
```
docker stop $(docker ps -a -q);
docker kill $(docker ps -a -q);
```
The problem was that ```docker ps -a -q``` will be executed on the host machine. Command substitution is as far as I know not possible in the way Envoy currently handles the ssh connection. By executing the script like: ```'echo \'' . $task->script . '\' | ssh '.$target.' \'bash -se\''``` it is possible to use Command Substitution because the script is rendered as string and then send to the remote machine.
Personaly I think it is more usefull to handle command substitution on the remote machine rather than on the host machine. Or was it completely intentional to handle this on the host machine?
PS the script keeps terminated when a non zero exit code is …
=> Added way in which you can run Command Substitutions on remote server

src/TaskContainer.php
Hi,
In case we want to execute to multiple servers and have the same Envoy script for multiple projects, it's preferable not to modify the list of servers multiple times (once in the servers list and for each task using them) but it should be better to regroup them with a single common name.
Example:
@servers(['bdd' => 'localhost', 'webs' => ['web1', 'web2']])
@task('test2', ['on' => 'webs'])
Thanks
=> Allow to use several servers with a single name

readme.md
The link to the official documentation was updated to always redirect to the last available documentation.
At this moment: https://laravel.com/docs/envoy -> https://laravel.com/docs/5.2/envoy
=> Documentation link updated to last available

src/RemoteProcessor.php
Update RemoteProcessor to use SSH with a heredoc to avoid quoting and escaping issues.
=> Fix RemoteProcess escape/quote issue

src/Console/RunCommand.php
Let's give a little more love to envoy.
Imagine we have a task like this:
```
@task('deploy')
git pull origin master
composer install -o
...
@if (!empty($cache))
// clear cache
@endif
@endtask
```
```envoy run deploy --cache```  doesn't work.
```envoy run deploy --cache=1``` does, but it's obviously not cool.
=> Support options without values

src/Console/RunCommand.php, src/TaskContainer.php
I made this change to allow for flexible reuse of tasks across macros. Any option set by a task can be overruled from the macro. This especially allows for tasks to be applied to specific sets of servers. 
**For example:**
```
@macro('deploy-staging', ['on' => ['stage-1', 'stage-2']])
...
@macro('deploy-production', ['on' => ['web-1', 'web-2']])
```
Both macros in this example would hold the same set of tasks, but they would only run on the servers the macros defined.
=> Allow macros to override their tasks with options.

.gitignore, src/SSHConfigFile.php
When you use ssh host with local user in your ssh config and trying to use @servers(['prod' => 'www@host']) - envoy uses your local user for ssh.
Commit fixes this problem.
=> Fixed ssh user@host when this host already used in ssh config without user

composer.json
When installing globally, it causes conflicts with other Laravel global packages. This fixes it.
=> Fixes dependency conflicts.

src/Compiler.php
We define all variables existing in the template, and check if it's already defined we return it as is, if not we return null.
That way there won't be any undefined variables in the file.
The compiled file will look like this:
```
<?php $test = isset($test) ? $test : null; ?>\n
<?php $message = isset($message) ? $message : null; ?>\n
<?php $__container = isset($__container) ? $__container : null; ?>\n
<?php $__container->servers(['server' => ['localhost']]); ?>\n
...
```
=> Initialize template variables

src/Compiler.php
When I updated to 1.3.0, I found that my Slack notifications were no longer printing out the task name that had been run (i.e. `Brian ran the [] task.`). I'm using the default Slack message that is created at https://github.com/laravel/envoy/blob/master/src/Slack.php#L54
**A compiled `@after` closure:**
```
<?php 
$_vars = get_defined_vars(); 
$__container->after(function($task) use ($_vars) { 
extract($_vars); 
Laravel\Envoy\Slack::make(...);
}); ?>
```
I found that because `$this->initializeVariables($value)` is run after compiling the statements down, a regression was introduced to the compiled $after closures.
**The following is added to the top of the compiled php file:**
```
<?php $_vars = isset($_vars) ? $_vars : null; ?>
<?php $task = isset($task) ? $task : null; ?>
<?php …
```
=> Fix regression for default Slack notification

src/Console/RunCommand.php
If a message comes with a blank line, it ignores all others lines.
=> Fix error output

src/Compiler.php, src/Console/RunCommand.php, src/TaskContainer.php, tests/CompilerTest.php
Add shutdown statement, this is another approach to resolve #96 .
problem: 
There is no callback for before shutdown.
After statement has been invoked after every task has been done.
If story has many tasks, it makes a bunch of notifications such as hipchat or slack.
I want callbacks for after command has been done.
solution:
I added shutdown statement which is called before shutdown.
I gave up to write tests.
Because it needs mockery and fix TaskContainer and RunCommand to use DI.
=> Add shutdown statement

src/Compiler.php, src/Hipchat.php, src/Slack.php
When using the @slack directive in the @finished one, there is a `Notice: Undefined variable: task` error when the envoy compiled file is ran because the slack object is not created in a task context.
This commit does 2 things :
1. Define locally an empty `$task` variable before instanciating the Slack or HipChat object to avoid the PHP error.
2. Define a more generic message if there is no task context to avoid message `User ran the [] task`. Default message in this case is `User ran a task`. One can still specify a message as third argument of course.
You can reproduce the error easily, use this `Envoy` file and run `envoy run test` :
```
@setup
$slack_webhook = '...';
$slack_channel = '...';
$remote_dir    = '/home/awesome_laravel_website';
@endsetup
@finished
@slack( $slack_webhook , …
```
=> fixed undefined $task error when using slack or hipchat

src/Console/RunCommand.php
This feature will allow users to override the expectaction that Envoy.blade.php is in the root of the project by supplying the full path on the system to Envoy.blade.php. Alternatively this could be implemented where they give just a path to the folder contianing the file. The current implementation expects the path and the filename.
=> ✨ 💡 Add flag to pass full path to Envoy.blade.php file

tests/TestCase.php
Use PSR-1 while extending PHPUnit TestCase class. This will help us when to migrate to PHPUnit 6, that no longer support snake case namespaces.
=> [1.3] Use PSR-1 in PHPunit TestCase

src/Console/RunCommand.php
In some cases we want to use multiple configuration files in one project. For example one main file for deployment and another for updating the local env or some local tasks. 
This wasn't possible because the hardcoded filename `Envoy.blade.php` can exist only once.
With this new option it is possible to load another configuration file like this: `envoy run XXX --file=EnvoyCustom.blade.php`.
=> Allow support for custom filename and multiple envoy files in one folder

src/Compiler.php
Add EXTR_SKIP to the extract() method in the after compiler method so the `$task` variable that is being passed as an attribute is not overwritten if it's being used in the after section or anywhere else.
Here's an example of a case where the value of `task` is being overwritten:
```blade
@servers(['web' => 'some-host'])
@task('run-something')
echo "hi"
@endtask
@error
if ($task == 'run-something') {
echo 'It failed';
}
@enderror
@after
// Here $task will be NULL because the variable $task will be initialized in the initializeVariables method,
// so after the extract() the value passed trough the call_user_func will be overwritten.
@endafter
```
=> Add EXTR_SKIP constant to the extract method in after compiler method

src/Compiler.php
Hi,
This PR allow to use variables (define in the `@setup` or passed down through cli) to be accessed and used in the `@error` directive.
=> Allow to use setup variables inside @error

src/Compiler.php
Add to the `error` callback the same fix used for the `after` callback.
=> Avoid $task overwrite on variables extract in the error callback

src/Console/RunCommand.php
Hi! With this PR, command:
```bash
php -f envoy run foo --conf=EnvoyCustom
```
is the same as command:
```bash
php -f envoy run foo --conf=EnvoyCustom.blade.php
```
=> Allow conf option without suffix in file name

bin/envoy, composer.json
This is the more common directory for binaries in packages. See https://github.com/php-pds/skeleton_research/blob/1.x/README.md#recommendation for a reference what the common directory structure looks like.
=> Move envoy cli to bin directory

src/TaskContainer.php
This will allow task arguments to override story/macro ones. This way specific tasks can have specific overrides when used in stories.
Closes https://github.com/laravel/envoy/issues/128
=> [2.x] Allow task arguments to override story ones

src/Console/RunCommand.php
Use different colors for each hosts so that it's easier to see which line was output on which host, especially when using parallel execution.
We cycle through yellow, cyan, magenta and blue (red, green and white are already used a lot in the logs themselves so I thought it best not to use them).
Here's a comparison of a deployment on 4 different servers with parallel execution, before and after :
=> Cycle through different colors for each host

.styleci.yml
Alpha ordered imports will become the default for the laravel preset in a few minutes time on styleci.io.
=> [1.x] Update .styleci.yml

src/RemoteProcessor.php
When upgrade dependency symfony/process to version ^5.0
We will got this error:
> Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /root/.composer/vendor/laravel/envoy/src/RemoteProcessor.php on line 62 and defined in /root/.composer/vendor/symfony/process/Process.php:140
So this pull request for resolve this issue.
I was tested on my local.
=> fix(Process): Convert command to array format

src/Console/SshCommand.php, src/Discord.php, src/Slack.php, src/TaskContainer.php
This PR fixes some spacing in docs, also adds some missing dockblocks.
Also, I wonder if wrapping the `$this->hook` in quotes is necessary:
https://github.com/laravel/envoy/pull/179/files#diff-377cfa899b27b5cdd529f8302f76e027R78
https://github.com/laravel/envoy/pull/179/files#diff-430f0452268eb52574d883c9eee27c50R88
=> [1.x] docs formatting

src/Console/RunCommand.php
I have added a limit to the explode of the argument to prevent losing a part of the argument when for example passing a url with query parameters with multiple = values in the argument value.
When passing a URL with query parameters as argument to Envoy, currently it explodes the = value which then is filled back in to the $options array. But by doing this, it losses argument values which has got more than 1 = statement in the argument value.
So for example the following command currently will result in this.
```php
php bin/envoy run foo --argument=http://domain.com?key=value
```
currently results into:
http://domain.com?key
instead of what it should be:
http://domain.com?key=value
So by adding a limit to the following explode
Currently:
```php
$option = explode('=', substr($argument, …
```
=> [1.x] Explode argument option issue losing a part of the argument when multiple = in one line is used

src/Compiler.php, src/Telegram.php
Added support for Telegram notifications using in your `Envoy.blade.php`:
```
@finished
@telegram('<bot-id>','<chat-id>', '<message = null>', '<options = []>')
@endfinished
```
You should have a proper `<bot-id>`, the id of the bot you're using to send messages. You can get one using an existing Telegram Bot or creating a new one using [BotFather](https://t.me/botfather).
Take a look at [Telegram Docs](https://core.telegram.org/bots/api#authorizing-your-bot) for additional information about Bot ids.
You should also use a valid `<chat-id>`, which is the id of the chat you want to send notifications. You can use the id of your own Telegram account if you want to send messages to yourself through the Bot, or you can use the id of a Telegram group (in which the Bot is invited / present).
You …
=> [2.x] Add Telegram notifications support

tests/CompilerTest.php, tests/SSHConfigFileTest.php
- Using the `assertSame` to replace `assertEquals` and it can make assertion equals checking strict.
=> Improve assertions

src/Console/RunCommand.php
This change allows for hyphenated options in envoy like so:
```bash
php artisan envoy run foo --no-npm
```
Which can be used as:
```blade
@task('foo', ['on' => 'localhost'])
@if (! $noNpm)
npm install
npm run prod
@endif
echo 'Task done'
@endtask
```
Since hyphenated options weren't usable before this won't break direct usage of those. However, it could be considered a breaking change if people were overwriting the command and expecting different keys from the `getOptions` method on the `RunCommand` class. But that seems unlikely to me.
Closes https://github.com/laravel/envoy/issues/211
=> [2.x] Allow hyphenated options

src/Compiler.php, src/Console/RunCommand.php
`@finished` is a catch-all which always runs, regardless of the result.
`@after` runs after _each task_, meaning stories end up firing many afters.
Currently, only error scenarios are handled discretely via `@error`. There is no explicit compliment to that for a success.
Ideally this would be something like `@success`. (I've PR'd that too: #219) However, this PR approaches the problem slightly differently by just using the callbacks we already have, not adding more.
The finished callbacks currently have very limited context about what's happened at the end of the task or story. While they're useful as a point to fire off alerts and cleanup tasks, the kind of logic you can write around those tasks is limited.
At the very minimum, having access to the **exit code** of the entire execution …
=> [2.x] Pass exit code to finished callbacks

src/Compiler.php, src/Console/RunCommand.php, src/TaskContainer.php
`@finished` is a catch-all which always runs, regardless of the result.
`@after` runs after each _task_, meaning _stories_ end up firing afters many times.
Currently, only error scenarios are handled discretely via `@error`. There is no explicit compliment to that for a success.
Ideally this would be something like `@success`. Hence this PR
=> [2.x] Add success callbacks

src/Compiler.php, src/MicrosoftTeams.php, src/Teams.php
Fixes #222 
This adds supporting of Microsoft Teams notifications. Ex:
```
@finished
@teams('teams-webhook', 'message = null', 'theme = 'success'', 'options = []')
@endfinished
```
**teams-webhook:  Required.**
You should create an incoming webhook for the selected channel to receive notifications, check [Teams incoming webhooks](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook) docs for more information.
**message:  Optional.**
Default value is Envoy default message, but you can overwrite it with your custom message.
**theme:  Optional.**
Default value is `success` for green color, but you can choose from three additional theme:
- `info` for cyan color
- `error` for red color
- `warning` for orange color
**options:  Optional.** …
=> Add Microsoft Teams notifications
